"""Morning briefing agent — gathers portfolio/technicals/news and sends AI analysis."""
import logging
from datetime import datetime

import pytz

import config
from core.telegram_bot import send_message
from data.news import get_news_sentiment_all_holdings
from data.portfolio import build_claude_context
from data.technicals import get_technicals_for_holdings

logger = logging.getLogger(__name__)

IST = pytz.timezone(config.TIMEZONE)


async def generate_briefing() -> dict:
    """Gather portfolio, technicals, and news then call the configured AI provider.

    Returns dict with keys: headline, alerts, watchlist, action_items.
    """
    portfolio_context = build_claude_context()
    technicals = get_technicals_for_holdings()
    news = get_news_sentiment_all_holdings()

    if config.AI_PROVIDER == "claude":
        from core.claude_client import call_claude_briefing
        return call_claude_briefing(portfolio_context, technicals, news)

    from core.openai_client import call_openai_briefing
    return call_openai_briefing(portfolio_context, technicals, news)


async def run_briefing() -> bool:
    """Generate and send the morning briefing to Telegram.

    Returns True on success, False if the AI call fails (fallback message still sent).
    """
    logger.info("Briefing: starting...")

    portfolio_context = build_claude_context()
    portfolio = portfolio_context.get("portfolio", {})
    total_value = portfolio.get("total_value", 0)
    total_pnl_pct = portfolio.get("total_pnl_pct", 0)
    count = portfolio.get("holdings_count", 0)
    today = datetime.now(IST).strftime("%a %d %b")

    try:
        result = await generate_briefing()
        success = True
    except Exception as exc:
        logger.error("Briefing AI call failed: %s", exc)
        result = {
            "headline": "Morning briefing — AI analysis unavailable.",
            "alerts": ["AI provider error — check logs."],
            "watchlist": [],
            "action_items": [
                "Review portfolio manually.",
                "Check API keys and connectivity.",
            ],
        }
        success = False

    alerts_block = "\n".join(f"• {a}" for a in result.get("alerts", [])) or "No alerts."
    watchlist_block = "\n".join(f"• {s}" for s in result.get("watchlist", [])) or "None."
    actions_block = "\n".join(
        f"{i + 1}. {a}" for i, a in enumerate(result.get("action_items", []))
    ) or "No actions."

    text = (
        f"☀️ <b>MORNING BRIEFING</b> — {today}\n"
        f"\n"
        f"📊 Portfolio: ₹{total_value:,.0f}\n"
        f"P&amp;L: {total_pnl_pct:+.1f}% | Holdings: {count}\n"
        f"\n"
        f"<b>📰 {result.get('headline', '')}</b>\n"
        f"\n"
        f"<b>Alerts</b>\n"
        f"{alerts_block}\n"
        f"\n"
        f"<b>Watchlist</b>\n"
        f"{watchlist_block}\n"
        f"\n"
        f"✅ <b>Top Actions</b>\n"
        f"{actions_block}\n"
        f"\n"
        f"🤖 <i>Generated by {config.AI_PROVIDER}</i>"
    )

    await send_message(text)
    logger.info("Briefing sent")
    return success
